name: Scrape Data Banjir

on:
  schedule:
    - cron: "*/30 * * * *"   # jalan setiap 30 minit
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_scrape.txt

      # ======================
      # Fix OpenSSL untuk benarkan legacy renegotiation
      # ======================
      - name: Enable legacy renegotiation
        run: |
          echo "openssl_conf = default_conf" > openssl.cnf
          echo "[default_conf]" >> openssl.cnf
          echo "ssl_conf = ssl_sect" >> openssl.cnf
          echo "[ssl_sect]" >> openssl.cnf
          echo "system_default = system_default_sect" >> openssl.cnf
          echo "[system_default_sect]" >> openssl.cnf
          echo "Options = UnsafeLegacyRenegotiation" >> openssl.cnf
          export OPENSSL_CONF=$PWD/openssl.cnf
          echo "OPENSSL_CONF=$PWD/openssl.cnf" >> $GITHUB_ENV

      # ======================
      # Download semua negeri
      # ======================
      - name: Download Negeri
        run: |
          mkdir -p raw
          wget --no-check-certificate --secure-protocol=auto -O raw/MLK.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=MLK&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/JHR.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=JHR&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/PHG.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=PHG&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/TRG.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=TRG&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/KTN.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=KTN&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/SWK.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=SWK&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/SBH.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=SBH&district=ALL&station=ALL&lang=en"
          wget --no-check-certificate --secure-protocol=auto -O raw/LBN.html "https://publicinfobanjir.water.gov.my/aras-air/data-paras-air-data/?state=LBN&district=ALL&station=ALL&lang=en"

      # ======================
      # Parse HTML ke JSON
      # ======================
      - name: Parse HTML ke JSON
        run: python scrape_banjir.py

      - name: Commit and push JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update data $(date)" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main
